name: DropProtect
main: com.virtivia.minecraft.bukkitplugins.dropprotect.DropProtect
version: 0.4.1
api-version: 1.18 
author: pavben
commands:
  dropprotect:
    description: Shows which item slots are protected on death.
    usage: /dropprotect
    permission:
    permission-message: N/A
